### ISSUE TITLE
使用报错connect ETIMEDOUT 112.124.219.244:8080

### ISSUE THREAD

**Issue by richenlin** [yi/node-oss-easy#4]
Error: connect ETIMEDOUT 112.124.219.244:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)

**Comment by yi** [comment]
是因为 阿里云近期关闭了 8080 端口的上传。请在使用的option中传入 `port:80` 就可以解决这个问题
